In [2]:
# Numpy의 임포트
import numpy

In [3]:
# 모듈에 다른 이름을 붙인다
import numpy as np

In [4]:
# 파이썬의 리스트로부터 넘파이 배열을 만든다
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])
print(a)

[0 1 2 3 4 5]


In [5]:
# 2중 리스트로부터 넘파이의 2차원 배열을 만든다
import numpy as np

b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [6]:
# 3중 리스트로부터 넘파이의 3차원 배열을 만든다
import numpy as np

c = np.array([[[0, 1, 2],[3, 4, 5]], [[5, 4, 3], [2, 1, 0]]])
print(c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


In [8]:
# 배열을 생성하는 다양한 함수
import numpy as np

d = np.zeros(8) # 0이 8개 저장된 배열
print(d)

e = np.ones(8) # 1이 8개 저장된 배열
print(e)

f = np.arange(8) # 0부터 7까지가 저장된 배열
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


In [10]:
# shape() 함수로 배열의 형태를 얻는다
import numpy as np
a = np.array([[0, 1, 2], 
             [3, 4, 5]]) # 2X3의 2차원 배열

print(np.shape(a))


(2, 3)


In [11]:
# len() 함수로 가장 바깥쪽의 요소 수를 구한다
print(len(a))

2


In [12]:
# 배열과 수치의 연산
import numpy as np

a = np.array([[0, 1, 2], 
              [3, 4, 5]]) # 2차원 배열

print(a)
print()
print(a + 3) # 각 요소에 3을 더한다
print()
print(a * 3) # 각 요소에 3을 곱한다

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [13]:
# 배열끼리의 연산
b = np.array([[0, 1, 2], 
              [3, 4, 5]])

c = np.array([[2, 0, 1], 
              [5, 3, 4]])

print(b)
print()
print(c)
print()
print(b + c)
print()
print(b * c)

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


In [14]:
# 인덱스를 지정하고, 배열의 요소로 접근한다
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[3]) # 인덱스를 지정


4


In [15]:
# 인덱스를 지정해서 배열의 요소를 바꾼다
a[2] = 9
print(a)

[1 2 9 4 5]


In [16]:
# 2차원 배열의 요소로 접근한다
b = np.array([[0, 1, 2], 
              [3, 4, 5]])
print(b[1, 2])
print(b[1][2])

5
5


In [18]:
# 2차원 배열의 요소를 바꾼다
b[1][2] = 9

print(b)

b[1, 2] = 8
print(b)

[[0 1 2]
 [3 4 9]]
[[0 1 2]
 [3 4 8]]


In [19]:
# 행이나 열에 접근한다
c = np.array([[0, 1, 2],
              [3, 4, 5]])

print(c[1, :]) # 인덱스가 1인 행을 취득

print()

c[:, 1] = np.array([6, 7]) # 인덱스가 1인 열을 교체
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]


In [20]:
# 함수의 인수, 반환값으로서의 배열
import numpy as np

def my_func(x):
    y = x * 2 + 1
    return y

a = np.array([[0, 1, 2],
              [3, 4, 5]]) 
b = my_func(a) # 인수로서 배열을 전달, 반환값으로서 배열을 받는다

print(b)

[[ 1  3  5]
 [ 7  9 11]]


In [21]:
# 넘파이가 가진 여러 가지 함수
import numpy as np

a = np.array([[0, 1, 2], 
              [3, 4, 5]])

print("합계:", np.sum(a))
print("평균:", np.average(a))
print("최댓값:", np.max(a))
print("최솟값:", np.min(a))

합계: 15
평균: 2.5
최댓값: 5
최솟값: 0


In [ ]:
# 합, 차, 곱
import numpy as np

a = np.array([[0, 1, 2], 
              [3, 4, 5]])

b = np.array([[5, 4, 3], 
              [2, 1, 0]])

print(a + b) # 합
print(a - b) # 차
print(a * b) # 곱

[[5 5 5]
 [5 5 5]]
[[-5 -3 -1]
 [ 1  3  5]]
[[0 4 6]
 [6 4 0]]
