In [1]:
import pandas as pd  # pandas 라이브러리 불러오기
import numpy as np  # numpy 라이브러리 불러오기

rng = np.random.RandomState(42)  # 랜덤 상태 설정
ser = pd.Series(rng.randint(0, 10, 4))  # 0에서 10 사이의 정수 4개로 시리즈 생성
ser  # 시리즈 출력

0    6
1    3
2    7
3    4
dtype: int64

In [2]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns = ['A', 'B', 'C', 'D'])

df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [3]:
np.exp(ser)  # 시리즈의 각 요소에 대해 자연 상수 e의 거듭제곱을 계산

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [4]:
np.sin(ser * np.pi / 4)  # 시리즈의 각 요소에 π/4를 곱한 후 사인 값을 계산

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [5]:
# 면적 데이터로 Series 생성
area = pd.Series({
    'Alaska': 1723337,      # 알래스카 면적
    'Texas': 695662,        # 텍사스 면적
    'California': 423967    # 캘리포니아 면적
}, name='area')             # Series 이름을 'area'로 지정

# 인구 데이터로 Series 생성
population = pd.Series({
    'California': 38332521, # 캘리포니아 인구
    'Texas': 26448193,      # 텍사스 인구
    'New York': 19651127    # 뉴욕 인구
}, name='population')       # Series 이름을 'population'으로 지정

In [6]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [7]:
area.index | population.index  # 두 Series의 인덱스에 대해 합집합 연산 수행

/var/folders/s4/vwxst1r92574j_j67vlznjq80000gn/T/ipykernel_1947/3572280633.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  area.index | population.index


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [8]:
# 첫 번째 Series 생성
A = pd.Series([2, 4, 6], index=[0, 1, 2])  # 인덱스 0,1,2에 대한 값 2,4,6

# 두 번째 Series 생성
B = pd.Series([1, 3, 5], index=[1, 2, 3])  # 인덱스 1,2,3에 대한 값 1,3,5

A + B  # Series 간 덧셈 수행 (인덱스 자동 정렬)

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [9]:
A.add(B, fill_value=0)  # Series 간 덧셈, 누락된 값은 0으로 처리

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [11]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),  # 0에서 20 사이의 랜덤 정수로 2x2 행렬 생성
                 columns=list('AB'))           # 열 이름을 'A'와 'B'로 지정

A  # DataFrame 출력

A   B
0   0  11
1  11  16

In [12]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),  # 0에서 9 사이의 랜덤 정수로 3x3 행렬 생성
                 columns=list('BAC'))          # 열 이름을 'B', 'A', 'C'로 지정

B  # DataFrame 출력

B  A  C
0  9  2  6
1  3  8  2
2  4  2  6

In [13]:
A + B

A     B   C
0   2.0  20.0 NaN
1  19.0  19.0 NaN
2   NaN   NaN NaN

In [14]:
# A의 모든 값의 평균을 계산
fill = A.stack().mean()  # stack()으로 1차원으로 변환 후 평균 계산

# A와 B를 더하면서 누락된 값은 평균값으로 대체
A.add(B, fill_value=fill)  # fill_value에 계산된 평균값 사용

A     B     C
0   2.0  20.0  15.5
1  19.0  19.0  11.5
2  11.5  13.5  15.5

In [15]:
A = rng.randint(10, size = (3, 4))
A

array([[4, 8, 6, 1],
       [3, 8, 1, 9],
       [8, 9, 4, 1]])

In [16]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1,  0, -5,  8],
       [ 4,  1, -2,  0]])

In [17]:
# 3x4 랜덤 배열 생성
A = rng.randint(10, size=(3, 4))  # 0부터 9까지의 랜덤 정수로 3x4 행렬 생성

A  # 배열 출력

A - A[0]  # 각 행에서 첫 번째 행을 뺌 (브로드캐스팅)

array([[ 0,  0,  0,  0],
       [-3, -3, -6,  5],
       [ 0, -5, -2,  3]])

In [18]:
df = pd.DataFrame(A, columns = list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -3 -3 -6  5
2  0 -5 -2  3

In [19]:
# 각 열에서 'R' 열을 뺌
df.subtract(df['R'], axis=0)  # axis=0: 행 방향으로 연산 수행

Q  R  S  T
0 -3  0  1 -4
1 -3  0 -2  4
2  2  0  4  4

In [20]:
halfrow = df.iloc[0, ::2]  # 첫 번째 행(0)에서 짝수 열만 선택
halfrow  # 결과 출력

Q    3
S    7
Name: 0, dtype: int64

In [21]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -3.0 NaN -6.0 NaN
2  0.0 NaN -2.0 NaN