In [1]:
import numpy
numpy.__version__

# 넘파이를 불러올거고, 버전 확인해주세요!

'1.26.4'

In [2]:
import numpy as np

# 넘파이를 불러올건데, 별칭은 np로 할겁니다.

In [3]:
import array
L = list(range(9+1))
A = array.array('i', L)
A


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 파이썬 리스트에서 배열 만들기
# 별칭 np로 표준 numpy를 임포트하기...
import numpy as np

# 정수 배열: 
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [5]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
# 명시적으로 결과 배열의 데이터 타입을 설정하려면 dtype 키워드를 사용하면 된다!
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [7]:
# 리스트를 중첩하면 다차원 배열이 된다!
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
# 처음부터 배열 만들기
# 0으로 채운 길이 10의 정수 배열 만들기
np.zeros(10, dtype=int)

# np를 불러와서 0으로 채울건데, 10개를 제한 조건으로 한 거고, 데이터 타입은 정수로 할거야...!

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 1로 채운 3X5 부동 소수점 배열 만들기
np.ones((3, 5), dtype=float)

# np를 불러와서 1로 채울건데, 3X5로 제한조건을 줄거고, 데이터 타입은 부동 소수점으로 줄거야..!

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# 3.14로 채운 3X5 배열 만들기
np.full((3,5), 3.14)

# np를 불러와서 채울건데, 우선 제한조건은 3X5이고, 3.14로 채울거야..!

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
# 선형 수열로 채운 배열 만들기
# 0에서 시작해 2씩 더해 20까지 채움
# 내장 함수인 range()와 유사함
np.arange(0, 20, 2)

# np를 불러와서 0부터 20까지 세워줄건데, 물론 20은 안들어갈거고,2씩 건너뛸겁니다..!

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
np.linspace(0, 1, 5)

# np를 불러와서 0과 1 사이의 균등한 간격을 가진 5개의 배열을 만들어주세요..!

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# 균등하게 분포된 3X3 배열 만들기
# 0과 1 사이의 난수로 채움
np.random.random((3,3))

array([[0.61229302, 0.15512438, 0.69873229],
       [0.01018411, 0.88939189, 0.6339914 ],
       [0.82984111, 0.38728759, 0.62503064]])

In [14]:
# 정규 분포(평균 = 0, 표준편차 = 1)의 난수로 채운 3X3 배열 만들기
np.random.normal(0, 1, (3, 3))

array([[ 1.30878795,  0.7768062 ,  0.92097561],
       [-0.65407525, -2.05464913, -0.26098132],
       [-0.11160006,  1.05480556, -0.15862319]])

In [15]:
# [0, 10] 구간의 임의의 정수로 채운 3X3 배열 만들기
np.random.randint(0, 10, (3,3))

array([[3, 9, 4],
       [9, 4, 0],
       [7, 1, 3]])

In [16]:
# 3X3 단위 행렬 만들기
np.eye(3)

# 지피티가 아래와 같이 말하네.. 왜 eye야..?라고 물으니까 , 
# "np.eye() 함수의 이름인 eye는 알파벳 I의 발음과 같습니다. 여기서 I는 수학에서 단위 행렬 (Identity Matrix) 을 의미합니다. 따라서 np.eye(3)은 3x3 단위 행렬을 생성합니다."
# 맞는지는 모르겠네...호호

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# 세 개의 정수를 가지는 초기화되지 않은 배열 만들기
# 값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움.
np.empty(3)

array([1., 1., 1.])

In [33]:
# numpy 배열 속성 지정
import numpy as np
np.random.seed(0) # 재현 가능성을 위한 시드 값

x1 = np.random.randint(10, size = 6) # 1차원 배열
x2 = np.random.randint(10, size = (3,4)) # 2차원 배열
x3 = np.random.randint(10, size = (3, 4, 5)) # 3차원 배열

print("x3 ndim: ", x3.ndim) # ndim(차원의 개수)
print("x3 shape: ", x3.shape) # shape(각 차원의 크기)
print("x3 size: ", x3.size) # size(전체 배열의 크기)
print("dtype: ", x3.dtype) # dtype(각 요소의 타입)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int64


In [34]:
# 배열 인덱싱 : 단일 요소에 접근하기
print(x1)
print(x1[0])
print(x1[4])
print(x1[-1])
print(x1[-2])

[5 0 3 3 7 9]
5
7
9
7


In [35]:
print(x2)
print(x2[0, 0])
print(x2[2, 0])
print(x2[2, -1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
1
7


In [36]:
x2[0, 0] = 12 

In [37]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
x1[0] = 3.141592 # 이 값의 소수점 이하는? 잘릴 것. 왜냐면 정수 배열에 부동 소수점을 값입하려고 하기 때문이다!!!
x1

array([3, 0, 3, 3, 7, 9])

In [39]:
# 배열 슬라이싱
# x[start:stop:step]

In [40]:
# 1차원 하위 배열
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x[:5] # 첫 다섯 개 요소

array([0, 1, 2, 3, 4])

In [42]:
x[5:] # 인덱스 5 다음 요소들

array([5, 6, 7, 8, 9])

In [43]:
x[4:7] # 중간 하위 배열


array([4, 5, 6])

In [44]:
x[::2] # 하나 걸러 하나씩의 요소로 구성된 배열

array([0, 2, 4, 6, 8])

In [45]:
x[1::2] # 인덱스 1에서 시작해 하나 걸러 하나씩 요소로 구성된 배열

array([1, 3, 5, 7, 9])

In [ ]:
x[::-1] # 모든 요소를 거꾸로 나열

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [47]:
x[5::-2] # 인덱스 5부터 하나 걸러 하나식 요소를 거꾸로 나열

array([5, 3, 1])

In [48]:
# 다차원 하위 배열
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [50]:
x2[:2, :3] # 두 개의 행, 세 개의 열

array([[12,  5,  2],
       [ 7,  6,  8]])

In [51]:
x2[:3, ::2] # 모든 행, 한 열 걸러 하나씩

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [52]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [53]:
print(x2[:, 0]) # x2의 첫 번째 열

[12  7  1]


In [54]:
print(x2[0, :])

[12  5  2  4]


In [55]:
print(x2[0]) # x[0, :]와 동일

[12  5  2  4]


In [56]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [57]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [62]:
x2_sub[0, 0] = 99
print(x2_sub)
print(" ")
print(x2)

[[99  5]
 [ 7  6]]
 
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [63]:
x_sub_copy = x2[:2, :2].copy()
print(x_sub_copy)

[[99  5]
 [ 7  6]]


In [64]:
x_sub_copy[0, 0] = 42
print(x_sub_copy)

print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [65]:
# 배열 재구조화
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
x = np.array([1, 2, 3])
# reshape을 이용한 행 벡터
x.reshape((1, 3))

array([[1, 2, 3]])

In [68]:
# newaxis를 이용한 행 벡터
x[np.newaxis, :]

array([[1, 2, 3]])

In [69]:
# reshape을 이용한 열 벡터
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [70]:
# newaxis를 이용한 열 벡터
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [71]:
# 배열 연결
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [72]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [73]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# 첫 번째 축을 따라 연결
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
# 두 번째 축을 따라 연결(0부터 시작하는 인덱스 방식)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [75]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], 
                 [6, 5, 4]])

# 배열을 수직으로 쌓음
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [76]:
# 배열을 수평으로 쌓음
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [77]:
# 배열 분할
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [78]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])