In [ ]:
import numpy
numpy.__version__

# 넘파이를 불러올거고, 버전 확인해주세요!

'1.26.4'

In [ ]:
import numpy as np

# 넘파이를 불러올건데, 별칭은 np로 할겁니다.

In [ ]:
import array
L = list(range(9+1))
A = array.array('i', L)
A


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# 파이썬 리스트에서 배열 만들기
# 별칭 np로 표준 numpy를 임포트하기...
import numpy as np

# 정수 배열: 
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [12]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
# 명시적으로 결과 배열의 데이터 타입을 설정하려면 dtype 키워드를 사용하면 된다!
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [14]:
# 리스트를 중첩하면 다차원 배열이 된다!
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# 처음부터 배열 만들기
# 0으로 채운 길이 10의 정수 배열 만들기
np.zeros(10, dtype=int)

# np를 불러와서 0으로 채울건데, 10개를 제한 조건으로 한 거고, 데이터 타입은 정수로 할거야...!

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# 1로 채운 3X5 부동 소수점 배열 만들기
np.ones((3, 5), dtype=float)

# np를 불러와서 1로 채울건데, 3X5로 제한조건을 줄거고, 데이터 타입은 부동 소수점으로 줄거야..!

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 3.14로 채운 3X5 배열 만들기
np.full((3,5), 3.14)

# np를 불러와서 채울건데, 우선 제한조건은 3X5이고, 3.14로 채울거야..!

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# 선형 수열로 채운 배열 만들기
# 0에서 시작해 2씩 더해 20까지 채움
# 내장 함수인 range()와 유사함
np.arange(0, 20, 2)

# np를 불러와서 0부터 20까지 세워줄건데, 물론 20은 안들어갈거고,2씩 건너뛸겁니다..!

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
np.linspace(0, 1, 5)

# np를 불러와서 0과 1 사이의 균등한 간격을 가진 5개의 배열을 만들어주세요..!

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
# 균등하게 분포된 3X3 배열 만들기
# 0과 1 사이의 난수로 채움
np.random.random((3,3))

array([[0.56593173, 0.07948078, 0.79397756],
       [0.37860884, 0.42018561, 0.54212502],
       [0.62026026, 0.97359869, 0.77703974]])

In [24]:
# 정규 분포(평균 = 0, 표준편차 = 1)의 난수로 채운 3X3 배열 만들기
np.random.normal(0, 1, (3, 3))

array([[-1.78068672, -0.20322047,  0.48601568],
       [ 1.29236047,  1.63346764, -0.65030699],
       [ 0.18081446,  1.67087266, -0.23097747]])

In [25]:
# [0, 10] 구간의 임의의 정수로 채운 3X3 배열 만들기
np.random.randint(0, 10, (3,3))

array([[7, 5, 6],
       [7, 9, 6],
       [3, 9, 8]])

In [ ]:
# 3X3 단위 행렬 만들기
np.eye(3)

# 지피티가 아래와 같이 말하네.. 왜 eye야..?라고 물으니까 , 
# "np.eye() 함수의 이름인 eye는 알파벳 I의 발음과 같습니다. 여기서 I는 수학에서 단위 행렬 (Identity Matrix) 을 의미합니다. 따라서 np.eye(3)은 3x3 단위 행렬을 생성합니다."
# 맞는지는 모르겠네...호호

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# 세 개의 정수를 가지는 초기화되지 않은 배열 만들기
# 값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움.
np.empty(3)

array([1., 1., 1.])

In [32]:
# numpy 배열 속성 지정
import numpy as np
np.random.seed(0) # 재현 가능성을 위한 시드 값

x1 = np.random.randint(10, size = 6) # 1차원 배열
x2 = np.random.randint(10, size = (3,4)) # 2차원 배열
x3 = np.random.randint(10, size = (3, 4, 5)) # 3차원 배열

print("x3 ndim: ", x3.ndim) # ndim(차원의 개수)
print("x3 shape: ", x3.shape) # shape(각 차원의 크기)
print("x3 size: ", x3.size) # size(전체 배열의 크기)
print("dtype: ", x3.dtype) # dtype(각 요소의 타입)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int64
